### PR TITLE
add dev env

### PR DESCRIPTION
**Pull request by maxiloc**

### CODE REVIEW

**Comment by vvo** [comment]
Add a note in the readme after tests and we're good to go

**Comment by vvo** [comment]
cc @maxiloc

**Comment by maxiloc** [comment]
Updated, not sure what to do for the node example, I'll let you add it if needed.

**Comment by vvo** [comment]
> It's a bit opinionated, since not every library is for use in UMD & in browser. Maybe a node example should be added as well?

Yes please do if you have 5 min, good idea

**Pull request merged**
